server:
  servlet:
    context-path: /api

spring:
  application:
    name: 'spring-project'

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

spring-project:
  kafka:
    topics:
      producer:
        metrics: t1_demo_metrics
        transaction-accept: t1_demo_transaction_accept
      consumer:
        accounts:
          id: spring-project-kafka-accounts
          name: t1_demo_accounts
        transactions:
          id: spring-project-kafka-transactions
          name: t1_demo_transactions
        transactions-result:
          id: spring-project-kafka-transactions-result
          name: t1_demo_transaction_result